apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workspace.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.workspace.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.workspace.taskSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.workspace.cachePvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.workspace.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.workspace.cacheSize }}
