{{- $queue := .Values.taskQueue | default (printf "proj-%s" .Values.project) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.project }}-worker
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.project }}-worker
  template:
    metadata:
      labels:
        app: {{ .Values.project }}-worker
    spec:
      serviceAccountName: {{ .Values.project }}-worker
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
      containers:
        - name: worker
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ .Values.temporal.address | quote }}
            - name: TEMPORAL_NAMESPACE
              value: {{ .Values.temporal.namespace | quote }}
            - name: PROJECT_TASK_QUEUE
              value: {{ $queue | quote }}
            {{- if .Values.otel.endpoint }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.endpoint | quote }}
            {{- end }}
          {{- if .Values.externalSecretRefs }}
          envFrom:
            {{- range .Values.externalSecretRefs }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}